config:
  libraries:
    k6:
      params:
        destination: k6
        source: github.com/aroq/toolbox-k6
        image: aroq/toolbox-k6
      commands:
        k6:
          params:
            cmd: k6/k6
tools:
  k6:
    from: config.libraries.k6.commands.k6
